import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import placementRouter from "./placement";
import levelsRouter from "./levels";
import lessonsRouter from "./lessons";
import exercisesRouter from "./exercises";
import vocabularyRouter from "./vocabulary";
import subscriptionsRouter from "./subscriptions";
import dashboardRouter from "./dashboard";
import reviewRouter from "./review";
import adminRouter from "./admin";
import languagesRouter from "./languages";
import cmsRouter from "./cms";
import quizzesRouter from "./quizzes";
import progressionRouter from "./progression";
import mediaRouter from "./media";
import adminAiRouter from "./admin-ai";
import conversationRouter from "./conversation";
import practiceRouter from "./practice";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(placementRouter);
router.use(levelsRouter);
router.use(lessonsRouter);
router.use(exercisesRouter);
router.use(vocabularyRouter);
router.use(subscriptionsRouter);
router.use(dashboardRouter);
router.use(reviewRouter);
router.use(adminRouter);
router.use(languagesRouter);
router.use(quizzesRouter);
router.use(progressionRouter);
router.use(mediaRouter);
router.use(adminAiRouter);
router.use(conversationRouter);
router.use(practiceRouter);
router.use(cmsRouter);

export default router;
